image: docker:19.03.12

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - deploy

services:
  - docker:19.03.12-dind

before_script:
  - apk install node
  - curl https://cli-assets.heroku.com/install.sh | sh

build:
  script:
    - npm ci
    - heroku login
