image: docker:19.03.12

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - deploy

services:
  - docker:19.03.12-dind

before_script:
  - apk add --update nodejs npm
  - curl https://cli-assets.heroku.com/install.sh | sh

build:
  stage: build
  script:
    - npm ci
    - heroku login
  except:
    refs:
      - master
      - hotfix-master

deploy:
  stage: deploy
  script:
    - npm ci
    - heroku login
  environment:
    name: staging
  only:
    refs:
      - develop
