image: $CI_CD_REGISTRY_IMAGE:latest

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  APP_NAME: cribstock-web

stages:
  - build
  - deploy

services:
  - docker:19.03.12-dind

build:
  stage: build
  script: cribstock build
  except:
    refs:
      - master
      - hotfix-master

deploy:
  stage: deploy
  script: cribstock deploy
  environment:
    name: staging
  only:
    refs:
      - develop
